### ISSUE TITLE
[Feature Request] Copy Credentials from HTTP Response

### ISSUE THREAD

**Issue by jjared** [anvilsecure/aws-sigv4#12]
It would be helpful to be able to send credentials directly from an HTTP response to the extension instead of having to manually copy/paste keys and tokens to profiles, especially because the profile editing screen can't be open on a different tab from the extension itself. This could be done either by right clicking the response or selecting it from a list in a popup. Often applications will use a login flow to get credentials which are returned in a JSON body that would be pretty simple to parse.

**Comment by UserExistsError** [comment]
Are you receiving credentials from [Cognito](https://docs.aws.amazon.com/cognitoidentity/latest/APIReference/API_GetCredentialsForIdentity.html#API_GetCredentialsForIdentity_ResponseSyntax)?

So a response like this one?

```
{
   "Credentials": { 
      "AccessKeyId": "string",
      "Expiration": number,
      "SecretKey": "string",
      "SessionToken": "string"
   },
   "IdentityId": "string"
}
```

I could add an item to the context menu for responses that allows users to highlight a JSON object and click "import" to open a profile dialog.

**Comment by UserExistsError** [comment]
I made a PR with this feature added. Feel free to try it out and comment in https://github.com/anvilsecure/aws-sigv4/pull/14
