### ISSUE TITLE
SessionToken not imported from Import, Auto

### ISSUE THREAD

**Issue by rbeede** [anvilsecure/aws-sigv4#17]
The SessionToken field is not populating when I import my .aws/credentials using the Import, Auto button.

The profile shows up after clicking on Auto, and I can click on Ok.

However, if I Edit the profile after that only the AccessKeyId and SecretKey are populated while SessionToken is blank.

My .aws/credentials file does have the expected "aws_session_token = IQ..."  value in it and from the aws cli it does work.

**Comment by UserExistsError** [comment]
Just merged https://github.com/anvilsecure/aws-sigv4/pull/18 which may fix this issue for you. Let me know!
